/**
 * Application Constants
 */

const ORDER_STATUS = {
  PENDING: 'PENDING',
  RESERVED: 'RESERVED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

const RESERVATION_STATUS = {
  ACTIVE: 'ACTIVE',
  RELEASED: 'RELEASED',
  CONVERTED: 'CONVERTED',
  EXPIRED: 'EXPIRED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMEOUT',
};

const PAYMENT_OUTCOME = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMEOUT',
};

// Stock reservation duration in milliseconds (5 minutes = 300,000 ms)
const RESERVATION_DURATION_MS = 5 * 60 * 1000;

// Valid state transitions for Order
const VALID_ORDER_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.RESERVED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.RESERVED]: [
    ORDER_STATUS.PAID,
    ORDER_STATUS.FAILED,
    ORDER_STATUS.CANCELLED,
    ORDER_STATUS.EXPIRED,
  ],
  [ORDER_STATUS.PAID]: [ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.FAILED]: [],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.EXPIRED]: [],
};

module.exports = {
  ORDER_STATUS,
  RESERVATION_STATUS,
  PAYMENT_STATUS,
  PAYMENT_OUTCOME,
  RESERVATION_DURATION_MS,
  VALID_ORDER_TRANSITIONS,
};
